services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_local
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXD_TRACKING_DISABLED=true
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password12345
      - DOCKER_INFLUXDB_INIT_ORG=fleet-org
      - DOCKER_INFLUXDB_INIT_BUCKET=fleet-telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  influxdb-setup:
    image: influxdb:2.7
    container_name: influxdb_setup
    depends_on:
      - influxdb
    entrypoint: ["/bin/sh", "-c"]
    restart: "no"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_local
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: